# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp
compiler: 
    - clang
#    - gcc
before_script:
    - git clone https://github.com/mokafolio/Stick.git
    - cd Stick
    - mkdir build && cd build && cmake .. && make install && cd ../..
    - mkdir build
    - cd build
    - cmake ..

script: make check
