# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp
compiler: 
    #- clang
    - gcc
# before_install:
#   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#   - sudo apt-get update
#   - sudo apt-get install -qq g++-5
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
before_script:
    - mkdir build
    - cd build
    - cmake -DBuildSubmodules=On ..
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    #- clang

script: make check
